Controllers/LogRegController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CSharpBeltTest.Models;
using Microsoft.EntityFrameworkCore;
using CSharpBeltTest.Controllers;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;


namespace LogReg.Controllers{
    public class LogRegController : Controller{
        private MyContext dbContext;
        public LogRegController(MyContext context)
        {
            dbContext = context;
        }
        public int? InSession {
            get { return HttpContext.Session.GetInt32("loggedUser"); }
            set { HttpContext.Session.SetInt32("loggedUser", (int)value); }
        }
        [HttpGet("")]
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost("register")]
        public IActionResult RegisterUser(Wrapper newUser){
            User nUser = newUser.thisUser;
            User dupe = dbContext.Users.FirstOrDefault(u => u.Email == newUser.thisUser.Email);
            if(dupe != null){
                ModelState.AddModelError("newUser.thisUser.Email", "Email already exists");
                return View("Index", newUser);
            }
            if(ModelState.IsValid){
                PasswordHasher<User> Hasher = new PasswordHasher<User>();
                nUser.Password = Hasher.HashPassword(nUser, nUser.Password);
                dbContext.Add(nUser);
                dbContext.SaveChanges();
                InSession = nUser.UserId;
                return RedirectToAction("Dashboard", "Home");
            } else {
                return View("Index", newUser);
            }
        }
        [HttpPost("login")]
        public IActionResult Login(Wrapper userLog){
            LoginUser logU = userLog.logUser;
            if(ModelState.IsValid){
                var userInDb = dbContext.Users.FirstOrDefault(u => u.Email == logU.Email);
                if(userInDb == null){
                    ModelState.AddModelError("userLog.logUser.Email", "Invalid Email.");
                    return View("Index", userLog);
                }
                var hasher = new PasswordHasher<LoginUser>();
                var result = hasher.VerifyHashedPassword(logU, userInDb.Password, logU.Password);
                if(result == 0){
                    ModelState.AddModelError("userLog.logUser.Password", "Wrong Password.");
                    return View("Index", userLog);
                }
                InSession = userInDb.UserId;
                return RedirectToAction("Dashboard", "Home");
            } else {
                return View("Index", userLog);
            }
        }
        
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

Views/LogReg/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model Wrapper
<div class="text-center">
    <h1 class="display-4">Welcome to the Dojo Activity Center</h1>
</div>
<br>
<div class="row">
    <div class="col-4 offset-2 text-center">
        <h2>Register</h2>
        <form class="text-left" asp-action="RegisterUser" asp-controller="LogReg" method="post">
            <span asp-validation-for="thisUser.Name"></span>
            <label asp-for="thisUser.Name"></label>
            <input class="form-control" asp-for="thisUser.Name">
            <br>
            <span asp-validation-for="thisUser.Email"></span>
            <label asp-for="thisUser.Email"></label>
            <input class="form-control" asp-for="thisUser.Email">
            <br>
            <span asp-validation-for="thisUser.Password"></span>
            <label asp-for="thisUser.Password"></label>
            <input class="form-control" asp-for="thisUser.Password">
            <br>
            <span asp-validation-for="thisUser.Confirm"></span>
            <label asp-for="thisUser.Confirm"></label>
            <input class="form-control" asp-for="thisUser.Confirm">
            <br>
            <input class="btn btn-primary" type="submit" value="Register">
        </form>
    </div>
    <div class="col-3 text-center">
        <h2>Login</h2>
        <form class="text-left" asp-action="Login" asp-controller="LogReg" method="post">
            <span asp-validation-for="logUser.Email"></span>
            <label asp-for="logUser.Email"></label>
            <input class="form-control" asp-for="logUser.Email">
            <br>
            <span asp-validation-for="logUser.Password"></span>
            <label asp-for="logUser.Password"></label>
            <input class="form-control" asp-for="logUser.Password">
            <br>
            <input class="btn btn-primary" type="submit" value="Log In">
        </form>
    </div>
</div>